// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pjmxxpagxlefalgltelb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBqbXh4cGFneGxlZmFsZ2x0ZWxiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU4NTcwNzAsImV4cCI6MjA2MTQzMzA3MH0.zJ5o-b2ErJFK6py_CEKhD7bHgdL3evouINCOs5oHCxw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);